//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kurs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kurs_Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kurs_Client()
        {
            this.Kurs_Request = new HashSet<Kurs_Request>();
        }
    
        public int IdClient { get; set; }
        public int UserId { get; set; }
        public System.DateTime Дата_рождения { get; set; }
        public int GenderId { get; set; }
        public int Возраст { get; set; }
        public int UnitId { get; set; }
    
        public virtual Kurs_User Kurs_User { get; set; }
        public virtual Kurs_Gender Kurs_Gender { get; set; }
        public virtual Kurs_Unit Kurs_Unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kurs_Request> Kurs_Request { get; set; }
    }
}
