//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kurs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kurs_ExerciseForDay
    {
        public int IdExerciseForDay { get; set; }
        public System.DateTime Дата_тренировки { get; set; }
        public string Упражнение { get; set; }
        public int UnitId { get; set; }
        public int TrainingProgramId { get; set; }
        public Nullable<int> PresenceId { get; set; }
    
        public virtual Kurs_Presence Kurs_Presence { get; set; }
        public virtual Kurs_Unit Kurs_Unit { get; set; }
        public virtual Kurs_TrainingProgram Kurs_TrainingProgram { get; set; }
    }
}
