//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kurs
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gr691_tkpEntities : DbContext
    {
        public gr691_tkpEntities()
            : base("name=gr691_tkpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kurs_Accept> Kurs_Accept { get; set; }
        public virtual DbSet<Kurs_Client> Kurs_Client { get; set; }
        public virtual DbSet<Kurs_ExerciseForDay> Kurs_ExerciseForDay { get; set; }
        public virtual DbSet<Kurs_Gender> Kurs_Gender { get; set; }
        public virtual DbSet<Kurs_Presence> Kurs_Presence { get; set; }
        public virtual DbSet<Kurs_Request> Kurs_Request { get; set; }
        public virtual DbSet<Kurs_Role> Kurs_Role { get; set; }
        public virtual DbSet<Kurs_Trainer> Kurs_Trainer { get; set; }
        public virtual DbSet<Kurs_TrainingProgram> Kurs_TrainingProgram { get; set; }
        public virtual DbSet<Kurs_Unit> Kurs_Unit { get; set; }
        public virtual DbSet<Kurs_User> Kurs_User { get; set; }
    }
}
